### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Exordian** [mattnovitsch/M365#1]
Thanks for the nice scripts in this repository!

As I couldn't find a license information, I'd kindly ask to consider adding a license file. The CustomInventory.ps1 script seems to be copied from the MS Intune repository [1] which is licensed under MIT license. The MIT license requires a copy of the MIT license anyways, therefore you could choose to license your whole repository under the MIT license.

Without a license [2] one shouldn't copy your work.

Thank you in advance!

[1] https://github.com/MSEndpointMgr/Intune/blob/master/LICENSE
[2] https://choosealicense.com/no-permission/

**Comment by mattnovitsch** [comment]
Thanks for the issue, I have added it to the main repository.
